name: quality-check

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        working-directory: ${{ inputs.working_directory }}
        run: uv python install 3.12

      - name: Sync dependencies
        working-directory: ${{ inputs.working_directory }}
        run: uv sync --all-extras

      - name: Lint
        working-directory: ${{ inputs.working_directory }}
        run: uv run ruff check

      - name: Check formatting
        working-directory: ${{ inputs.working_directory }}
        run: uv run ruff format --check

      - name: Type check
        working-directory: ${{ inputs.working_directory }}
        run: uv run pyright
      
      - name: Start docker compose
        working-directory: ./libraries/dagster-iceberg/docker
        run: WAREHOUSE_PATH=./tmpwarehouse2 docker compose up --build --wait

      - name: Test
        working-directory: ${{ inputs.working_directory }}
        run: uv run pytest
